project:
  type: website

website:
  site-url: "https://bakhtawarhalepoto.github.io/minidocsite-Bakhtawar/"
  page-footer:
    background: primary
    left: "&copy;2026, Bakhtawar Halepoto"
    center: "Built with [Quarto](https://quarto.org)"
    right:
     - icon: github
       href: "https://github.com/bakhtawar"


  title: "My Mini Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - article1.qmd
      - article2.qmd
      - article3.qmd   

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true